package com.Pranav.finance_tracker.financialintelligence.entity;

import com.Pranav.finance_tracker.financialintelligence.risk.FinancialRiskType;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A single personalized financial insight generated by the Financial Intelligence Engine.
 *
 * <p>Insights are produced nightly by the rule engine and consumed by the frontend
 * "AI Insights" page. The entity is intentionally decoupled from the {@code User}
 * object graph (it references the owner by {@code userId} only) so the
 * {@code financialintelligence} module stays isolated from other business modules.</p>
 */
@Entity
@Table(
        name = "financial_insights",
        indexes = {
                @Index(name = "idx_insight_user_created", columnList = "user_id, created_at"),
                @Index(name = "idx_insight_user_rule_created", columnList = "user_id, rule_key, created_at")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FinancialInsight {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owner of the insight. Stored by id to keep the module self-contained. */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /**
     * Stable identifier of the rule (optionally parameterized, e.g. {@code BUDGET_USAGE:Food})
     * that produced this insight. Used to prevent generating the same insight twice in one day.
     */
    @Column(name = "rule_key", nullable = false, length = 120)
    private String ruleKey;

    @Column(nullable = false, length = 160)
    private String title;

    @Column(nullable = false, length = 1000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "insight_type", nullable = false, length = 40)
    private InsightType insightType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Severity severity;

    /**
     * Risk classification for insights produced by the Risk Detection Engine (Module 2),
     * or {@code null} for plain spending-intelligence insights. Persisted so the API and
     * frontend can filter/group by risk type without inspecting the rule that created it.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_type", length = 40)
    private FinancialRiskType riskType;

    /** Business category the insight relates to (e.g. "Food"), or {@code null} if not category-scoped. */
    @Column(length = 80)
    private String category;

    @Column(name = "action_suggestion", length = 1000)
    private String actionSuggestion;

    /** Engine confidence in this insight, in the range [0.0, 1.0]. */
    @Column(nullable = false)
    private double confidence;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** After this instant the insight is considered stale and hidden from active queries. */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    /** Whether the user has opened/read the insight. */
    @Column(nullable = false)
    private boolean viewed;

    /** Whether the user has explicitly dismissed the insight. */
    @Column(nullable = false)
    private boolean dismissed;
}
